/**
 * Carbon
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AddWebhookProps model module.
 * @module model/AddWebhookProps
 * @version 1.0.0
 */
class AddWebhookProps {
    /**
     * Constructs a new <code>AddWebhookProps</code>.
     * @alias module:model/AddWebhookProps
     * @param url {Object} 
     */
    constructor(url) { 
        
        AddWebhookProps.initialize(this, url);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, url) { 
        obj['url'] = url;
    }

    /**
     * Constructs a <code>AddWebhookProps</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddWebhookProps} obj Optional instance to populate.
     * @return {module:model/AddWebhookProps} The populated <code>AddWebhookProps</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddWebhookProps();

            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AddWebhookProps</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AddWebhookProps</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AddWebhookProps.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

AddWebhookProps.RequiredProperties = ["url"];

/**
 * @member {Object} url
 */
AddWebhookProps.prototype['url'] = undefined;






export default AddWebhookProps;

