/**
 * Carbon
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EmbeddingsAndChunksFiltersEmbeddingModel from './EmbeddingsAndChunksFiltersEmbeddingModel';

/**
 * The EmbeddingsAndChunksFilters model module.
 * @module model/EmbeddingsAndChunksFilters
 * @version 1.0.0
 */
class EmbeddingsAndChunksFilters {
    /**
     * Constructs a new <code>EmbeddingsAndChunksFilters</code>.
     * @alias module:model/EmbeddingsAndChunksFilters
     * @param userFileId {Object} 
     */
    constructor(userFileId) { 
        
        EmbeddingsAndChunksFilters.initialize(this, userFileId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, userFileId) { 
        obj['user_file_id'] = userFileId;
    }

    /**
     * Constructs a <code>EmbeddingsAndChunksFilters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EmbeddingsAndChunksFilters} obj Optional instance to populate.
     * @return {module:model/EmbeddingsAndChunksFilters} The populated <code>EmbeddingsAndChunksFilters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EmbeddingsAndChunksFilters();

            if (data.hasOwnProperty('user_file_id')) {
                obj['user_file_id'] = ApiClient.convertToType(data['user_file_id'], Object);
            }
            if (data.hasOwnProperty('embedding_model')) {
                obj['embedding_model'] = EmbeddingsAndChunksFiltersEmbeddingModel.constructFromObject(data['embedding_model']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EmbeddingsAndChunksFilters</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EmbeddingsAndChunksFilters</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EmbeddingsAndChunksFilters.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `embedding_model`
        if (data['embedding_model']) { // data not null
          EmbeddingsAndChunksFiltersEmbeddingModel.validateJSON(data['embedding_model']);
        }

        return true;
    }


}

EmbeddingsAndChunksFilters.RequiredProperties = ["user_file_id"];

/**
 * @member {Object} user_file_id
 */
EmbeddingsAndChunksFilters.prototype['user_file_id'] = undefined;

/**
 * @member {module:model/EmbeddingsAndChunksFiltersEmbeddingModel} embedding_model
 */
EmbeddingsAndChunksFilters.prototype['embedding_model'] = undefined;






export default EmbeddingsAndChunksFilters;

