/**
 * Carbon
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EmbeddingsAndChunksFilters from './EmbeddingsAndChunksFilters';
import EmbeddingsAndChunksOrderByColumns from './EmbeddingsAndChunksOrderByColumns';
import OrderDir from './OrderDir';
import Pagination from './Pagination';

/**
 * The EmbeddingsAndChunksQueryInput model module.
 * @module model/EmbeddingsAndChunksQueryInput
 * @version 1.0.0
 */
class EmbeddingsAndChunksQueryInput {
    /**
     * Constructs a new <code>EmbeddingsAndChunksQueryInput</code>.
     * @alias module:model/EmbeddingsAndChunksQueryInput
     * @param filters {module:model/EmbeddingsAndChunksFilters} 
     */
    constructor(filters) { 
        
        EmbeddingsAndChunksQueryInput.initialize(this, filters);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, filters) { 
        obj['filters'] = filters;
    }

    /**
     * Constructs a <code>EmbeddingsAndChunksQueryInput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EmbeddingsAndChunksQueryInput} obj Optional instance to populate.
     * @return {module:model/EmbeddingsAndChunksQueryInput} The populated <code>EmbeddingsAndChunksQueryInput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EmbeddingsAndChunksQueryInput();

            if (data.hasOwnProperty('pagination')) {
                obj['pagination'] = ApiClient.convertToType(data['pagination'], Pagination);
            }
            if (data.hasOwnProperty('order_by')) {
                obj['order_by'] = ApiClient.convertToType(data['order_by'], EmbeddingsAndChunksOrderByColumns);
            }
            if (data.hasOwnProperty('order_dir')) {
                obj['order_dir'] = ApiClient.convertToType(data['order_dir'], OrderDir);
            }
            if (data.hasOwnProperty('filters')) {
                obj['filters'] = EmbeddingsAndChunksFilters.constructFromObject(data['filters']);
            }
            if (data.hasOwnProperty('include_vectors')) {
                obj['include_vectors'] = ApiClient.convertToType(data['include_vectors'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EmbeddingsAndChunksQueryInput</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EmbeddingsAndChunksQueryInput</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EmbeddingsAndChunksQueryInput.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `pagination`
        if (data['pagination']) { // data not null
          Pagination.validateJSON(data['pagination']);
        }
        // validate the optional field `filters`
        if (data['filters']) { // data not null
          EmbeddingsAndChunksFilters.validateJSON(data['filters']);
        }

        return true;
    }


}

EmbeddingsAndChunksQueryInput.RequiredProperties = ["filters"];

/**
 * @member {module:model/Pagination} pagination
 */
EmbeddingsAndChunksQueryInput.prototype['pagination'] = undefined;

/**
 * @member {module:model/EmbeddingsAndChunksOrderByColumns} order_by
 */
EmbeddingsAndChunksQueryInput.prototype['order_by'] = undefined;

/**
 * @member {module:model/OrderDir} order_dir
 */
EmbeddingsAndChunksQueryInput.prototype['order_dir'] = undefined;

/**
 * @member {module:model/EmbeddingsAndChunksFilters} filters
 */
EmbeddingsAndChunksQueryInput.prototype['filters'] = undefined;

/**
 * @member {Object} include_vectors
 */
EmbeddingsAndChunksQueryInput.prototype['include_vectors'] = undefined;






export default EmbeddingsAndChunksQueryInput;

