/**
 * Carbon
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FetchURLsResponse model module.
 * @module model/FetchURLsResponse
 * @version 1.0.0
 */
class FetchURLsResponse {
    /**
     * Constructs a new <code>FetchURLsResponse</code>.
     * @alias module:model/FetchURLsResponse
     * @param urls {Object} 
     * @param htmlContent {Object} 
     */
    constructor(urls, htmlContent) { 
        
        FetchURLsResponse.initialize(this, urls, htmlContent);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, urls, htmlContent) { 
        obj['urls'] = urls;
        obj['html_content'] = htmlContent;
    }

    /**
     * Constructs a <code>FetchURLsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FetchURLsResponse} obj Optional instance to populate.
     * @return {module:model/FetchURLsResponse} The populated <code>FetchURLsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FetchURLsResponse();

            if (data.hasOwnProperty('urls')) {
                obj['urls'] = ApiClient.convertToType(data['urls'], Object);
            }
            if (data.hasOwnProperty('html_content')) {
                obj['html_content'] = ApiClient.convertToType(data['html_content'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FetchURLsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FetchURLsResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of FetchURLsResponse.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

FetchURLsResponse.RequiredProperties = ["urls", "html_content"];

/**
 * @member {Object} urls
 */
FetchURLsResponse.prototype['urls'] = undefined;

/**
 * @member {Object} html_content
 */
FetchURLsResponse.prototype['html_content'] = undefined;






export default FetchURLsResponse;

