/**
 * Carbon
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HybridSearchTuningParams model module.
 * @module model/HybridSearchTuningParams
 * @version 1.0.0
 */
class HybridSearchTuningParams {
    /**
     * Constructs a new <code>HybridSearchTuningParams</code>.
     * @alias module:model/HybridSearchTuningParams
     * @param weightA {Object} 
     * @param weightB {Object} 
     */
    constructor(weightA, weightB) { 
        
        HybridSearchTuningParams.initialize(this, weightA, weightB);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, weightA, weightB) { 
        obj['weight_a'] = weightA;
        obj['weight_b'] = weightB;
    }

    /**
     * Constructs a <code>HybridSearchTuningParams</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HybridSearchTuningParams} obj Optional instance to populate.
     * @return {module:model/HybridSearchTuningParams} The populated <code>HybridSearchTuningParams</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HybridSearchTuningParams();

            if (data.hasOwnProperty('weight_a')) {
                obj['weight_a'] = ApiClient.convertToType(data['weight_a'], Object);
            }
            if (data.hasOwnProperty('weight_b')) {
                obj['weight_b'] = ApiClient.convertToType(data['weight_b'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HybridSearchTuningParams</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HybridSearchTuningParams</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of HybridSearchTuningParams.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

HybridSearchTuningParams.RequiredProperties = ["weight_a", "weight_b"];

/**
 * @member {Object} weight_a
 */
HybridSearchTuningParams.prototype['weight_a'] = undefined;

/**
 * @member {Object} weight_b
 */
HybridSearchTuningParams.prototype['weight_b'] = undefined;






export default HybridSearchTuningParams;

