/**
 * Carbon
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Pagination from './Pagination';
import ParentId from './ParentId';

/**
 * The ListDataSourceItemsRequest model module.
 * @module model/ListDataSourceItemsRequest
 * @version 1.0.0
 */
class ListDataSourceItemsRequest {
    /**
     * Constructs a new <code>ListDataSourceItemsRequest</code>.
     * @alias module:model/ListDataSourceItemsRequest
     * @param dataSourceId {Object} 
     */
    constructor(dataSourceId) { 
        
        ListDataSourceItemsRequest.initialize(this, dataSourceId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, dataSourceId) { 
        obj['data_source_id'] = dataSourceId;
    }

    /**
     * Constructs a <code>ListDataSourceItemsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListDataSourceItemsRequest} obj Optional instance to populate.
     * @return {module:model/ListDataSourceItemsRequest} The populated <code>ListDataSourceItemsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListDataSourceItemsRequest();

            if (data.hasOwnProperty('data_source_id')) {
                obj['data_source_id'] = ApiClient.convertToType(data['data_source_id'], Object);
            }
            if (data.hasOwnProperty('parent_id')) {
                obj['parent_id'] = ParentId.constructFromObject(data['parent_id']);
            }
            if (data.hasOwnProperty('pagination')) {
                obj['pagination'] = ApiClient.convertToType(data['pagination'], Pagination);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListDataSourceItemsRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ListDataSourceItemsRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ListDataSourceItemsRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `parent_id`
        if (data['parent_id']) { // data not null
          ParentId.validateJSON(data['parent_id']);
        }
        // validate the optional field `pagination`
        if (data['pagination']) { // data not null
          Pagination.validateJSON(data['pagination']);
        }

        return true;
    }


}

ListDataSourceItemsRequest.RequiredProperties = ["data_source_id"];

/**
 * @member {Object} data_source_id
 */
ListDataSourceItemsRequest.prototype['data_source_id'] = undefined;

/**
 * @member {module:model/ParentId} parent_id
 */
ListDataSourceItemsRequest.prototype['parent_id'] = undefined;

/**
 * @member {module:model/Pagination} pagination
 */
ListDataSourceItemsRequest.prototype['pagination'] = undefined;






export default ListDataSourceItemsRequest;

