/**
 * Carbon
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ModifyUserConfigurationInput model module.
 * @module model/ModifyUserConfigurationInput
 * @version 1.0.0
 */
class ModifyUserConfigurationInput {
    /**
     * Constructs a new <code>ModifyUserConfigurationInput</code>.
     * @alias module:model/ModifyUserConfigurationInput
     * @param configurationKeyName {Object} 
     * @param value {Object} 
     */
    constructor(configurationKeyName, value) { 
        
        ModifyUserConfigurationInput.initialize(this, configurationKeyName, value);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, configurationKeyName, value) { 
        obj['configuration_key_name'] = configurationKeyName;
        obj['value'] = value;
    }

    /**
     * Constructs a <code>ModifyUserConfigurationInput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModifyUserConfigurationInput} obj Optional instance to populate.
     * @return {module:model/ModifyUserConfigurationInput} The populated <code>ModifyUserConfigurationInput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModifyUserConfigurationInput();

            if (data.hasOwnProperty('configuration_key_name')) {
                obj['configuration_key_name'] = ApiClient.convertToType(data['configuration_key_name'], Object);
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ModifyUserConfigurationInput</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ModifyUserConfigurationInput</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ModifyUserConfigurationInput.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

ModifyUserConfigurationInput.RequiredProperties = ["configuration_key_name", "value"];

/**
 * @member {Object} configuration_key_name
 */
ModifyUserConfigurationInput.prototype['configuration_key_name'] = undefined;

/**
 * @member {Object} value
 */
ModifyUserConfigurationInput.prototype['value'] = undefined;






export default ModifyUserConfigurationInput;

