/**
 * Carbon
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IncludeAdditionalFiles from './IncludeAdditionalFiles';
import IncludeParsedTextFile from './IncludeParsedTextFile';
import IncludeRawFile1 from './IncludeRawFile1';
import OrderDir from './OrderDir';
import OrganizationUserFilesToSyncFilters from './OrganizationUserFilesToSyncFilters';
import OrganizationUserFilesToSyncOrderByTypes from './OrganizationUserFilesToSyncOrderByTypes';
import Pagination from './Pagination';

/**
 * The OrganizationUserFilesToSyncQueryInput model module.
 * @module model/OrganizationUserFilesToSyncQueryInput
 * @version 1.0.0
 */
class OrganizationUserFilesToSyncQueryInput {
    /**
     * Constructs a new <code>OrganizationUserFilesToSyncQueryInput</code>.
     * @alias module:model/OrganizationUserFilesToSyncQueryInput
     */
    constructor() { 
        
        OrganizationUserFilesToSyncQueryInput.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OrganizationUserFilesToSyncQueryInput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrganizationUserFilesToSyncQueryInput} obj Optional instance to populate.
     * @return {module:model/OrganizationUserFilesToSyncQueryInput} The populated <code>OrganizationUserFilesToSyncQueryInput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrganizationUserFilesToSyncQueryInput();

            if (data.hasOwnProperty('pagination')) {
                obj['pagination'] = ApiClient.convertToType(data['pagination'], Pagination);
            }
            if (data.hasOwnProperty('order_by')) {
                obj['order_by'] = ApiClient.convertToType(data['order_by'], OrganizationUserFilesToSyncOrderByTypes);
            }
            if (data.hasOwnProperty('order_dir')) {
                obj['order_dir'] = ApiClient.convertToType(data['order_dir'], OrderDir);
            }
            if (data.hasOwnProperty('filters')) {
                obj['filters'] = ApiClient.convertToType(data['filters'], OrganizationUserFilesToSyncFilters);
            }
            if (data.hasOwnProperty('include_raw_file')) {
                obj['include_raw_file'] = IncludeRawFile1.constructFromObject(data['include_raw_file']);
            }
            if (data.hasOwnProperty('include_parsed_text_file')) {
                obj['include_parsed_text_file'] = IncludeParsedTextFile.constructFromObject(data['include_parsed_text_file']);
            }
            if (data.hasOwnProperty('include_additional_files')) {
                obj['include_additional_files'] = IncludeAdditionalFiles.constructFromObject(data['include_additional_files']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OrganizationUserFilesToSyncQueryInput</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OrganizationUserFilesToSyncQueryInput</code>.
     */
    static validateJSON(data) {
        // validate the optional field `pagination`
        if (data['pagination']) { // data not null
          Pagination.validateJSON(data['pagination']);
        }
        // validate the optional field `filters`
        if (data['filters']) { // data not null
          OrganizationUserFilesToSyncFilters.validateJSON(data['filters']);
        }
        // validate the optional field `include_raw_file`
        if (data['include_raw_file']) { // data not null
          IncludeRawFile1.validateJSON(data['include_raw_file']);
        }
        // validate the optional field `include_parsed_text_file`
        if (data['include_parsed_text_file']) { // data not null
          IncludeParsedTextFile.validateJSON(data['include_parsed_text_file']);
        }
        // validate the optional field `include_additional_files`
        if (data['include_additional_files']) { // data not null
          IncludeAdditionalFiles.validateJSON(data['include_additional_files']);
        }

        return true;
    }


}



/**
 * @member {module:model/Pagination} pagination
 */
OrganizationUserFilesToSyncQueryInput.prototype['pagination'] = undefined;

/**
 * @member {module:model/OrganizationUserFilesToSyncOrderByTypes} order_by
 */
OrganizationUserFilesToSyncQueryInput.prototype['order_by'] = undefined;

/**
 * @member {module:model/OrderDir} order_dir
 */
OrganizationUserFilesToSyncQueryInput.prototype['order_dir'] = undefined;

/**
 * @member {module:model/OrganizationUserFilesToSyncFilters} filters
 */
OrganizationUserFilesToSyncQueryInput.prototype['filters'] = undefined;

/**
 * @member {module:model/IncludeRawFile1} include_raw_file
 */
OrganizationUserFilesToSyncQueryInput.prototype['include_raw_file'] = undefined;

/**
 * @member {module:model/IncludeParsedTextFile} include_parsed_text_file
 */
OrganizationUserFilesToSyncQueryInput.prototype['include_parsed_text_file'] = undefined;

/**
 * @member {module:model/IncludeAdditionalFiles} include_additional_files
 */
OrganizationUserFilesToSyncQueryInput.prototype['include_additional_files'] = undefined;






export default OrganizationUserFilesToSyncQueryInput;

