/**
 * Carbon
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OrganizationUserFileTagsRemove model module.
 * @module model/OrganizationUserFileTagsRemove
 * @version 1.0.0
 */
class OrganizationUserFileTagsRemove {
    /**
     * Constructs a new <code>OrganizationUserFileTagsRemove</code>.
     * @alias module:model/OrganizationUserFileTagsRemove
     * @param organizationUserFileId {Object} 
     * @param tags {Object} 
     */
    constructor(organizationUserFileId, tags) { 
        
        OrganizationUserFileTagsRemove.initialize(this, organizationUserFileId, tags);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, organizationUserFileId, tags) { 
        obj['organization_user_file_id'] = organizationUserFileId;
        obj['tags'] = tags;
    }

    /**
     * Constructs a <code>OrganizationUserFileTagsRemove</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrganizationUserFileTagsRemove} obj Optional instance to populate.
     * @return {module:model/OrganizationUserFileTagsRemove} The populated <code>OrganizationUserFileTagsRemove</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrganizationUserFileTagsRemove();

            if (data.hasOwnProperty('organization_user_file_id')) {
                obj['organization_user_file_id'] = ApiClient.convertToType(data['organization_user_file_id'], Object);
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OrganizationUserFileTagsRemove</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OrganizationUserFileTagsRemove</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of OrganizationUserFileTagsRemove.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

OrganizationUserFileTagsRemove.RequiredProperties = ["organization_user_file_id", "tags"];

/**
 * @member {Object} organization_user_file_id
 */
OrganizationUserFileTagsRemove.prototype['organization_user_file_id'] = undefined;

/**
 * @member {Object} tags
 */
OrganizationUserFileTagsRemove.prototype['tags'] = undefined;






export default OrganizationUserFileTagsRemove;

