/**
 * Carbon
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RevokeAccessTokenInput model module.
 * @module model/RevokeAccessTokenInput
 * @version 1.0.0
 */
class RevokeAccessTokenInput {
    /**
     * Constructs a new <code>RevokeAccessTokenInput</code>.
     * @alias module:model/RevokeAccessTokenInput
     * @param dataSourceId {Object} 
     */
    constructor(dataSourceId) { 
        
        RevokeAccessTokenInput.initialize(this, dataSourceId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, dataSourceId) { 
        obj['data_source_id'] = dataSourceId;
    }

    /**
     * Constructs a <code>RevokeAccessTokenInput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RevokeAccessTokenInput} obj Optional instance to populate.
     * @return {module:model/RevokeAccessTokenInput} The populated <code>RevokeAccessTokenInput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RevokeAccessTokenInput();

            if (data.hasOwnProperty('data_source_id')) {
                obj['data_source_id'] = ApiClient.convertToType(data['data_source_id'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RevokeAccessTokenInput</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RevokeAccessTokenInput</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RevokeAccessTokenInput.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

RevokeAccessTokenInput.RequiredProperties = ["data_source_id"];

/**
 * @member {Object} data_source_id
 */
RevokeAccessTokenInput.prototype['data_source_id'] = undefined;






export default RevokeAccessTokenInput;

