/**
 * Carbon
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The S3AuthRequest model module.
 * @module model/S3AuthRequest
 * @version 1.0.0
 */
class S3AuthRequest {
    /**
     * Constructs a new <code>S3AuthRequest</code>.
     * @alias module:model/S3AuthRequest
     * @param accessKey {Object} 
     * @param accessKeySecret {Object} 
     */
    constructor(accessKey, accessKeySecret) { 
        
        S3AuthRequest.initialize(this, accessKey, accessKeySecret);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, accessKey, accessKeySecret) { 
        obj['access_key'] = accessKey;
        obj['access_key_secret'] = accessKeySecret;
    }

    /**
     * Constructs a <code>S3AuthRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/S3AuthRequest} obj Optional instance to populate.
     * @return {module:model/S3AuthRequest} The populated <code>S3AuthRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new S3AuthRequest();

            if (data.hasOwnProperty('access_key')) {
                obj['access_key'] = ApiClient.convertToType(data['access_key'], Object);
            }
            if (data.hasOwnProperty('access_key_secret')) {
                obj['access_key_secret'] = ApiClient.convertToType(data['access_key_secret'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>S3AuthRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>S3AuthRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of S3AuthRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

S3AuthRequest.RequiredProperties = ["access_key", "access_key_secret"];

/**
 * @member {Object} access_key
 */
S3AuthRequest.prototype['access_key'] = undefined;

/**
 * @member {Object} access_key_secret
 */
S3AuthRequest.prototype['access_key_secret'] = undefined;






export default S3AuthRequest;

