/**
 * Carbon
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Bucket from './Bucket';
import Id from './Id';

/**
 * The S3GetFileInput model module.
 * @module model/S3GetFileInput
 * @version 1.0.0
 */
class S3GetFileInput {
    /**
     * Constructs a new <code>S3GetFileInput</code>.
     * @alias module:model/S3GetFileInput
     */
    constructor() { 
        
        S3GetFileInput.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>S3GetFileInput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/S3GetFileInput} obj Optional instance to populate.
     * @return {module:model/S3GetFileInput} The populated <code>S3GetFileInput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new S3GetFileInput();

            if (data.hasOwnProperty('id')) {
                obj['id'] = Id.constructFromObject(data['id']);
            }
            if (data.hasOwnProperty('bucket')) {
                obj['bucket'] = Bucket.constructFromObject(data['bucket']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>S3GetFileInput</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>S3GetFileInput</code>.
     */
    static validateJSON(data) {
        // validate the optional field `id`
        if (data['id']) { // data not null
          Id.validateJSON(data['id']);
        }
        // validate the optional field `bucket`
        if (data['bucket']) { // data not null
          Bucket.validateJSON(data['bucket']);
        }

        return true;
    }


}



/**
 * @member {module:model/Id} id
 */
S3GetFileInput.prototype['id'] = undefined;

/**
 * @member {module:model/Bucket} bucket
 */
S3GetFileInput.prototype['bucket'] = undefined;






export default S3GetFileInput;

