/**
 * Carbon
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ChunkOverlap from './ChunkOverlap';
import ChunkSize from './ChunkSize';

/**
 * The SingleChunksAndEmbeddingsUploadInput model module.
 * @module model/SingleChunksAndEmbeddingsUploadInput
 * @version 1.0.0
 */
class SingleChunksAndEmbeddingsUploadInput {
    /**
     * Constructs a new <code>SingleChunksAndEmbeddingsUploadInput</code>.
     * @alias module:model/SingleChunksAndEmbeddingsUploadInput
     * @param fileId {Object} 
     * @param chunksAndEmbeddings {Object} 
     */
    constructor(fileId, chunksAndEmbeddings) { 
        
        SingleChunksAndEmbeddingsUploadInput.initialize(this, fileId, chunksAndEmbeddings);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, fileId, chunksAndEmbeddings) { 
        obj['file_id'] = fileId;
        obj['chunks_and_embeddings'] = chunksAndEmbeddings;
    }

    /**
     * Constructs a <code>SingleChunksAndEmbeddingsUploadInput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SingleChunksAndEmbeddingsUploadInput} obj Optional instance to populate.
     * @return {module:model/SingleChunksAndEmbeddingsUploadInput} The populated <code>SingleChunksAndEmbeddingsUploadInput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SingleChunksAndEmbeddingsUploadInput();

            if (data.hasOwnProperty('file_id')) {
                obj['file_id'] = ApiClient.convertToType(data['file_id'], Object);
            }
            if (data.hasOwnProperty('chunk_size')) {
                obj['chunk_size'] = ChunkSize.constructFromObject(data['chunk_size']);
            }
            if (data.hasOwnProperty('chunk_overlap')) {
                obj['chunk_overlap'] = ChunkOverlap.constructFromObject(data['chunk_overlap']);
            }
            if (data.hasOwnProperty('chunks_and_embeddings')) {
                obj['chunks_and_embeddings'] = ApiClient.convertToType(data['chunks_and_embeddings'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SingleChunksAndEmbeddingsUploadInput</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SingleChunksAndEmbeddingsUploadInput</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SingleChunksAndEmbeddingsUploadInput.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `chunk_size`
        if (data['chunk_size']) { // data not null
          ChunkSize.validateJSON(data['chunk_size']);
        }
        // validate the optional field `chunk_overlap`
        if (data['chunk_overlap']) { // data not null
          ChunkOverlap.validateJSON(data['chunk_overlap']);
        }

        return true;
    }


}

SingleChunksAndEmbeddingsUploadInput.RequiredProperties = ["file_id", "chunks_and_embeddings"];

/**
 * @member {Object} file_id
 */
SingleChunksAndEmbeddingsUploadInput.prototype['file_id'] = undefined;

/**
 * @member {module:model/ChunkSize} chunk_size
 */
SingleChunksAndEmbeddingsUploadInput.prototype['chunk_size'] = undefined;

/**
 * @member {module:model/ChunkOverlap} chunk_overlap
 */
SingleChunksAndEmbeddingsUploadInput.prototype['chunk_overlap'] = undefined;

/**
 * @member {Object} chunks_and_embeddings
 */
SingleChunksAndEmbeddingsUploadInput.prototype['chunks_and_embeddings'] = undefined;






export default SingleChunksAndEmbeddingsUploadInput;

