/**
 * Carbon
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DeletedAt from './DeletedAt';
import EnabledFeatures from './EnabledFeatures';

/**
 * The UserResponse model module.
 * @module model/UserResponse
 * @version 1.0.0
 */
class UserResponse {
    /**
     * Constructs a new <code>UserResponse</code>.
     * @alias module:model/UserResponse
     * @param id {Object} 
     * @param organizationId {Object} 
     * @param organizationSuppliedUserId {Object} 
     * @param createdAt {Object} 
     * @param updatedAt {Object} 
     * @param deletedAt {module:model/DeletedAt} 
     * @param numFilesSynced {Object} 
     * @param numCharactersSynced {Object} 
     * @param numTokensSynced {Object} 
     * @param uniqueFileTags {Object} 
     * @param enabledFeatures {module:model/EnabledFeatures} 
     */
    constructor(id, organizationId, organizationSuppliedUserId, createdAt, updatedAt, deletedAt, numFilesSynced, numCharactersSynced, numTokensSynced, uniqueFileTags, enabledFeatures) { 
        
        UserResponse.initialize(this, id, organizationId, organizationSuppliedUserId, createdAt, updatedAt, deletedAt, numFilesSynced, numCharactersSynced, numTokensSynced, uniqueFileTags, enabledFeatures);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, organizationId, organizationSuppliedUserId, createdAt, updatedAt, deletedAt, numFilesSynced, numCharactersSynced, numTokensSynced, uniqueFileTags, enabledFeatures) { 
        obj['id'] = id;
        obj['organization_id'] = organizationId;
        obj['organization_supplied_user_id'] = organizationSuppliedUserId;
        obj['created_at'] = createdAt;
        obj['updated_at'] = updatedAt;
        obj['deleted_at'] = deletedAt;
        obj['num_files_synced'] = numFilesSynced;
        obj['num_characters_synced'] = numCharactersSynced;
        obj['num_tokens_synced'] = numTokensSynced;
        obj['unique_file_tags'] = uniqueFileTags;
        obj['enabled_features'] = enabledFeatures;
    }

    /**
     * Constructs a <code>UserResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserResponse} obj Optional instance to populate.
     * @return {module:model/UserResponse} The populated <code>UserResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], Object);
            }
            if (data.hasOwnProperty('organization_id')) {
                obj['organization_id'] = ApiClient.convertToType(data['organization_id'], Object);
            }
            if (data.hasOwnProperty('organization_supplied_user_id')) {
                obj['organization_supplied_user_id'] = ApiClient.convertToType(data['organization_supplied_user_id'], Object);
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], Object);
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], Object);
            }
            if (data.hasOwnProperty('deleted_at')) {
                obj['deleted_at'] = DeletedAt.constructFromObject(data['deleted_at']);
            }
            if (data.hasOwnProperty('num_files_synced')) {
                obj['num_files_synced'] = ApiClient.convertToType(data['num_files_synced'], Object);
            }
            if (data.hasOwnProperty('num_characters_synced')) {
                obj['num_characters_synced'] = ApiClient.convertToType(data['num_characters_synced'], Object);
            }
            if (data.hasOwnProperty('num_tokens_synced')) {
                obj['num_tokens_synced'] = ApiClient.convertToType(data['num_tokens_synced'], Object);
            }
            if (data.hasOwnProperty('unique_file_tags')) {
                obj['unique_file_tags'] = ApiClient.convertToType(data['unique_file_tags'], Object);
            }
            if (data.hasOwnProperty('enabled_features')) {
                obj['enabled_features'] = EnabledFeatures.constructFromObject(data['enabled_features']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UserResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UserResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UserResponse.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `deleted_at`
        if (data['deleted_at']) { // data not null
          DeletedAt.validateJSON(data['deleted_at']);
        }
        // validate the optional field `enabled_features`
        if (data['enabled_features']) { // data not null
          EnabledFeatures.validateJSON(data['enabled_features']);
        }

        return true;
    }


}

UserResponse.RequiredProperties = ["id", "organization_id", "organization_supplied_user_id", "created_at", "updated_at", "deleted_at", "num_files_synced", "num_characters_synced", "num_tokens_synced", "unique_file_tags", "enabled_features"];

/**
 * @member {Object} id
 */
UserResponse.prototype['id'] = undefined;

/**
 * @member {Object} organization_id
 */
UserResponse.prototype['organization_id'] = undefined;

/**
 * @member {Object} organization_supplied_user_id
 */
UserResponse.prototype['organization_supplied_user_id'] = undefined;

/**
 * @member {Object} created_at
 */
UserResponse.prototype['created_at'] = undefined;

/**
 * @member {Object} updated_at
 */
UserResponse.prototype['updated_at'] = undefined;

/**
 * @member {module:model/DeletedAt} deleted_at
 */
UserResponse.prototype['deleted_at'] = undefined;

/**
 * @member {Object} num_files_synced
 */
UserResponse.prototype['num_files_synced'] = undefined;

/**
 * @member {Object} num_characters_synced
 */
UserResponse.prototype['num_characters_synced'] = undefined;

/**
 * @member {Object} num_tokens_synced
 */
UserResponse.prototype['num_tokens_synced'] = undefined;

/**
 * @member {Object} unique_file_tags
 */
UserResponse.prototype['unique_file_tags'] = undefined;

/**
 * @member {module:model/EnabledFeatures} enabled_features
 */
UserResponse.prototype['enabled_features'] = undefined;






export default UserResponse;

