/**
 * Carbon
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Ids1 from './Ids1';

/**
 * The WebhookFilters model module.
 * @module model/WebhookFilters
 * @version 1.0.0
 */
class WebhookFilters {
    /**
     * Constructs a new <code>WebhookFilters</code>.
     * @alias module:model/WebhookFilters
     */
    constructor() { 
        
        WebhookFilters.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WebhookFilters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WebhookFilters} obj Optional instance to populate.
     * @return {module:model/WebhookFilters} The populated <code>WebhookFilters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WebhookFilters();

            if (data.hasOwnProperty('ids')) {
                obj['ids'] = Ids1.constructFromObject(data['ids']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WebhookFilters</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WebhookFilters</code>.
     */
    static validateJSON(data) {
        // validate the optional field `ids`
        if (data['ids']) { // data not null
          Ids1.validateJSON(data['ids']);
        }

        return true;
    }


}



/**
 * @member {module:model/Ids1} ids
 */
WebhookFilters.prototype['ids'] = undefined;






export default WebhookFilters;

