/**
 * Carbon
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ChunkOverlap1 from './ChunkOverlap1';
import ChunkSize1 from './ChunkSize1';
import CssClassesToSkip from './CssClassesToSkip';
import CssSelectorsToSkip from './CssSelectorsToSkip';
import EnableAutoSync from './EnableAutoSync';
import GenerateSparseVectors from './GenerateSparseVectors';
import HtmlTagsToSkip from './HtmlTagsToSkip';
import MaxPagesToScrape from './MaxPagesToScrape';
import PrependFilenameToChunks from './PrependFilenameToChunks';
import RecursionDepth from './RecursionDepth';
import SkipEmbeddingGeneration from './SkipEmbeddingGeneration';
import Tags5 from './Tags5';

/**
 * The WebscrapeRequest model module.
 * @module model/WebscrapeRequest
 * @version 1.0.0
 */
class WebscrapeRequest {
    /**
     * Constructs a new <code>WebscrapeRequest</code>.
     * @alias module:model/WebscrapeRequest
     * @param url {Object} 
     */
    constructor(url) { 
        
        WebscrapeRequest.initialize(this, url);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, url) { 
        obj['url'] = url;
    }

    /**
     * Constructs a <code>WebscrapeRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WebscrapeRequest} obj Optional instance to populate.
     * @return {module:model/WebscrapeRequest} The populated <code>WebscrapeRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WebscrapeRequest();

            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], Object);
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = Tags5.constructFromObject(data['tags']);
            }
            if (data.hasOwnProperty('recursion_depth')) {
                obj['recursion_depth'] = RecursionDepth.constructFromObject(data['recursion_depth']);
            }
            if (data.hasOwnProperty('max_pages_to_scrape')) {
                obj['max_pages_to_scrape'] = MaxPagesToScrape.constructFromObject(data['max_pages_to_scrape']);
            }
            if (data.hasOwnProperty('chunk_size')) {
                obj['chunk_size'] = ChunkSize1.constructFromObject(data['chunk_size']);
            }
            if (data.hasOwnProperty('chunk_overlap')) {
                obj['chunk_overlap'] = ChunkOverlap1.constructFromObject(data['chunk_overlap']);
            }
            if (data.hasOwnProperty('skip_embedding_generation')) {
                obj['skip_embedding_generation'] = SkipEmbeddingGeneration.constructFromObject(data['skip_embedding_generation']);
            }
            if (data.hasOwnProperty('enable_auto_sync')) {
                obj['enable_auto_sync'] = EnableAutoSync.constructFromObject(data['enable_auto_sync']);
            }
            if (data.hasOwnProperty('generate_sparse_vectors')) {
                obj['generate_sparse_vectors'] = GenerateSparseVectors.constructFromObject(data['generate_sparse_vectors']);
            }
            if (data.hasOwnProperty('prepend_filename_to_chunks')) {
                obj['prepend_filename_to_chunks'] = PrependFilenameToChunks.constructFromObject(data['prepend_filename_to_chunks']);
            }
            if (data.hasOwnProperty('html_tags_to_skip')) {
                obj['html_tags_to_skip'] = HtmlTagsToSkip.constructFromObject(data['html_tags_to_skip']);
            }
            if (data.hasOwnProperty('css_classes_to_skip')) {
                obj['css_classes_to_skip'] = CssClassesToSkip.constructFromObject(data['css_classes_to_skip']);
            }
            if (data.hasOwnProperty('css_selectors_to_skip')) {
                obj['css_selectors_to_skip'] = CssSelectorsToSkip.constructFromObject(data['css_selectors_to_skip']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WebscrapeRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WebscrapeRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WebscrapeRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `tags`
        if (data['tags']) { // data not null
          Tags5.validateJSON(data['tags']);
        }
        // validate the optional field `recursion_depth`
        if (data['recursion_depth']) { // data not null
          RecursionDepth.validateJSON(data['recursion_depth']);
        }
        // validate the optional field `max_pages_to_scrape`
        if (data['max_pages_to_scrape']) { // data not null
          MaxPagesToScrape.validateJSON(data['max_pages_to_scrape']);
        }
        // validate the optional field `chunk_size`
        if (data['chunk_size']) { // data not null
          ChunkSize1.validateJSON(data['chunk_size']);
        }
        // validate the optional field `chunk_overlap`
        if (data['chunk_overlap']) { // data not null
          ChunkOverlap1.validateJSON(data['chunk_overlap']);
        }
        // validate the optional field `skip_embedding_generation`
        if (data['skip_embedding_generation']) { // data not null
          SkipEmbeddingGeneration.validateJSON(data['skip_embedding_generation']);
        }
        // validate the optional field `enable_auto_sync`
        if (data['enable_auto_sync']) { // data not null
          EnableAutoSync.validateJSON(data['enable_auto_sync']);
        }
        // validate the optional field `generate_sparse_vectors`
        if (data['generate_sparse_vectors']) { // data not null
          GenerateSparseVectors.validateJSON(data['generate_sparse_vectors']);
        }
        // validate the optional field `prepend_filename_to_chunks`
        if (data['prepend_filename_to_chunks']) { // data not null
          PrependFilenameToChunks.validateJSON(data['prepend_filename_to_chunks']);
        }
        // validate the optional field `html_tags_to_skip`
        if (data['html_tags_to_skip']) { // data not null
          HtmlTagsToSkip.validateJSON(data['html_tags_to_skip']);
        }
        // validate the optional field `css_classes_to_skip`
        if (data['css_classes_to_skip']) { // data not null
          CssClassesToSkip.validateJSON(data['css_classes_to_skip']);
        }
        // validate the optional field `css_selectors_to_skip`
        if (data['css_selectors_to_skip']) { // data not null
          CssSelectorsToSkip.validateJSON(data['css_selectors_to_skip']);
        }

        return true;
    }


}

WebscrapeRequest.RequiredProperties = ["url"];

/**
 * @member {Object} url
 */
WebscrapeRequest.prototype['url'] = undefined;

/**
 * @member {module:model/Tags5} tags
 */
WebscrapeRequest.prototype['tags'] = undefined;

/**
 * @member {module:model/RecursionDepth} recursion_depth
 */
WebscrapeRequest.prototype['recursion_depth'] = undefined;

/**
 * @member {module:model/MaxPagesToScrape} max_pages_to_scrape
 */
WebscrapeRequest.prototype['max_pages_to_scrape'] = undefined;

/**
 * @member {module:model/ChunkSize1} chunk_size
 */
WebscrapeRequest.prototype['chunk_size'] = undefined;

/**
 * @member {module:model/ChunkOverlap1} chunk_overlap
 */
WebscrapeRequest.prototype['chunk_overlap'] = undefined;

/**
 * @member {module:model/SkipEmbeddingGeneration} skip_embedding_generation
 */
WebscrapeRequest.prototype['skip_embedding_generation'] = undefined;

/**
 * @member {module:model/EnableAutoSync} enable_auto_sync
 */
WebscrapeRequest.prototype['enable_auto_sync'] = undefined;

/**
 * @member {module:model/GenerateSparseVectors} generate_sparse_vectors
 */
WebscrapeRequest.prototype['generate_sparse_vectors'] = undefined;

/**
 * @member {module:model/PrependFilenameToChunks} prepend_filename_to_chunks
 */
WebscrapeRequest.prototype['prepend_filename_to_chunks'] = undefined;

/**
 * @member {module:model/HtmlTagsToSkip} html_tags_to_skip
 */
WebscrapeRequest.prototype['html_tags_to_skip'] = undefined;

/**
 * @member {module:model/CssClassesToSkip} css_classes_to_skip
 */
WebscrapeRequest.prototype['css_classes_to_skip'] = undefined;

/**
 * @member {module:model/CssSelectorsToSkip} css_selectors_to_skip
 */
WebscrapeRequest.prototype['css_selectors_to_skip'] = undefined;






export default WebscrapeRequest;

