/**
 * Carbon
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CarbonJsSdk);
  }
}(this, function(expect, CarbonJsSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CarbonJsSdk.DocumentResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DocumentResponse', function() {
    it('should create an instance of DocumentResponse', function() {
      // uncomment below and update the code to test DocumentResponse
      //var instance = new CarbonJsSdk.DocumentResponse();
      //expect(instance).to.be.a(CarbonJsSdk.DocumentResponse);
    });

    it('should have the property content (base name: "content")', function() {
      // uncomment below and update the code to test the property content
      //var instance = new CarbonJsSdk.DocumentResponse();
      //expect(instance).to.be();
    });

    it('should have the property fileId (base name: "file_id")', function() {
      // uncomment below and update the code to test the property fileId
      //var instance = new CarbonJsSdk.DocumentResponse();
      //expect(instance).to.be();
    });

    it('should have the property source (base name: "source")', function() {
      // uncomment below and update the code to test the property source
      //var instance = new CarbonJsSdk.DocumentResponse();
      //expect(instance).to.be();
    });

    it('should have the property sourceUrl (base name: "source_url")', function() {
      // uncomment below and update the code to test the property sourceUrl
      //var instance = new CarbonJsSdk.DocumentResponse();
      //expect(instance).to.be();
    });

    it('should have the property sourceType (base name: "source_type")', function() {
      // uncomment below and update the code to test the property sourceType
      //var instance = new CarbonJsSdk.DocumentResponse();
      //expect(instance).to.be();
    });

    it('should have the property presignedUrl (base name: "presigned_url")', function() {
      // uncomment below and update the code to test the property presignedUrl
      //var instance = new CarbonJsSdk.DocumentResponse();
      //expect(instance).to.be();
    });

    it('should have the property tags (base name: "tags")', function() {
      // uncomment below and update the code to test the property tags
      //var instance = new CarbonJsSdk.DocumentResponse();
      //expect(instance).to.be();
    });

    it('should have the property vector (base name: "vector")', function() {
      // uncomment below and update the code to test the property vector
      //var instance = new CarbonJsSdk.DocumentResponse();
      //expect(instance).to.be();
    });

    it('should have the property score (base name: "score")', function() {
      // uncomment below and update the code to test the property score
      //var instance = new CarbonJsSdk.DocumentResponse();
      //expect(instance).to.be();
    });

    it('should have the property rank (base name: "rank")', function() {
      // uncomment below and update the code to test the property rank
      //var instance = new CarbonJsSdk.DocumentResponse();
      //expect(instance).to.be();
    });

    it('should have the property contentMetadata (base name: "content_metadata")', function() {
      // uncomment below and update the code to test the property contentMetadata
      //var instance = new CarbonJsSdk.DocumentResponse();
      //expect(instance).to.be();
    });

  });

}));
