/**
 * Carbon
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CarbonJsSdk);
  }
}(this, function(expect, CarbonJsSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CarbonJsSdk.ExternalSourceItem();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ExternalSourceItem', function() {
    it('should create an instance of ExternalSourceItem', function() {
      // uncomment below and update the code to test ExternalSourceItem
      //var instance = new CarbonJsSdk.ExternalSourceItem();
      //expect(instance).to.be.a(CarbonJsSdk.ExternalSourceItem);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new CarbonJsSdk.ExternalSourceItem();
      //expect(instance).to.be();
    });

    it('should have the property externalId (base name: "external_id")', function() {
      // uncomment below and update the code to test the property externalId
      //var instance = new CarbonJsSdk.ExternalSourceItem();
      //expect(instance).to.be();
    });

    it('should have the property source (base name: "source")', function() {
      // uncomment below and update the code to test the property source
      //var instance = new CarbonJsSdk.ExternalSourceItem();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new CarbonJsSdk.ExternalSourceItem();
      //expect(instance).to.be();
    });

    it('should have the property syncedAt (base name: "synced_at")', function() {
      // uncomment below and update the code to test the property syncedAt
      //var instance = new CarbonJsSdk.ExternalSourceItem();
      //expect(instance).to.be();
    });

    it('should have the property isSelectable (base name: "is_selectable")', function() {
      // uncomment below and update the code to test the property isSelectable
      //var instance = new CarbonJsSdk.ExternalSourceItem();
      //expect(instance).to.be();
    });

    it('should have the property isExpandable (base name: "is_expandable")', function() {
      // uncomment below and update the code to test the property isExpandable
      //var instance = new CarbonJsSdk.ExternalSourceItem();
      //expect(instance).to.be();
    });

    it('should have the property organizationId (base name: "organization_id")', function() {
      // uncomment below and update the code to test the property organizationId
      //var instance = new CarbonJsSdk.ExternalSourceItem();
      //expect(instance).to.be();
    });

    it('should have the property organizationSuppliedUserId (base name: "organization_supplied_user_id")', function() {
      // uncomment below and update the code to test the property organizationSuppliedUserId
      //var instance = new CarbonJsSdk.ExternalSourceItem();
      //expect(instance).to.be();
    });

    it('should have the property organizationUserId (base name: "organization_user_id")', function() {
      // uncomment below and update the code to test the property organizationUserId
      //var instance = new CarbonJsSdk.ExternalSourceItem();
      //expect(instance).to.be();
    });

    it('should have the property organizationUserDataSourceId (base name: "organization_user_data_source_id")', function() {
      // uncomment below and update the code to test the property organizationUserDataSourceId
      //var instance = new CarbonJsSdk.ExternalSourceItem();
      //expect(instance).to.be();
    });

    it('should have the property organizationUserFileToSyncId (base name: "organization_user_file_to_sync_id")', function() {
      // uncomment below and update the code to test the property organizationUserFileToSyncId
      //var instance = new CarbonJsSdk.ExternalSourceItem();
      //expect(instance).to.be();
    });

    it('should have the property parentExternalId (base name: "parent_external_id")', function() {
      // uncomment below and update the code to test the property parentExternalId
      //var instance = new CarbonJsSdk.ExternalSourceItem();
      //expect(instance).to.be();
    });

    it('should have the property itemType (base name: "item_type")', function() {
      // uncomment below and update the code to test the property itemType
      //var instance = new CarbonJsSdk.ExternalSourceItem();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new CarbonJsSdk.ExternalSourceItem();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new CarbonJsSdk.ExternalSourceItem();
      //expect(instance).to.be();
    });

  });

}));
