/**
 * Carbon
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CarbonJsSdk);
  }
}(this, function(expect, CarbonJsSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CarbonJsSdk.OrganizationUserFilesToSyncQueryInput();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OrganizationUserFilesToSyncQueryInput', function() {
    it('should create an instance of OrganizationUserFilesToSyncQueryInput', function() {
      // uncomment below and update the code to test OrganizationUserFilesToSyncQueryInput
      //var instance = new CarbonJsSdk.OrganizationUserFilesToSyncQueryInput();
      //expect(instance).to.be.a(CarbonJsSdk.OrganizationUserFilesToSyncQueryInput);
    });

    it('should have the property pagination (base name: "pagination")', function() {
      // uncomment below and update the code to test the property pagination
      //var instance = new CarbonJsSdk.OrganizationUserFilesToSyncQueryInput();
      //expect(instance).to.be();
    });

    it('should have the property orderBy (base name: "order_by")', function() {
      // uncomment below and update the code to test the property orderBy
      //var instance = new CarbonJsSdk.OrganizationUserFilesToSyncQueryInput();
      //expect(instance).to.be();
    });

    it('should have the property orderDir (base name: "order_dir")', function() {
      // uncomment below and update the code to test the property orderDir
      //var instance = new CarbonJsSdk.OrganizationUserFilesToSyncQueryInput();
      //expect(instance).to.be();
    });

    it('should have the property filters (base name: "filters")', function() {
      // uncomment below and update the code to test the property filters
      //var instance = new CarbonJsSdk.OrganizationUserFilesToSyncQueryInput();
      //expect(instance).to.be();
    });

    it('should have the property includeRawFile (base name: "include_raw_file")', function() {
      // uncomment below and update the code to test the property includeRawFile
      //var instance = new CarbonJsSdk.OrganizationUserFilesToSyncQueryInput();
      //expect(instance).to.be();
    });

    it('should have the property includeParsedTextFile (base name: "include_parsed_text_file")', function() {
      // uncomment below and update the code to test the property includeParsedTextFile
      //var instance = new CarbonJsSdk.OrganizationUserFilesToSyncQueryInput();
      //expect(instance).to.be();
    });

    it('should have the property includeAdditionalFiles (base name: "include_additional_files")', function() {
      // uncomment below and update the code to test the property includeAdditionalFiles
      //var instance = new CarbonJsSdk.OrganizationUserFilesToSyncQueryInput();
      //expect(instance).to.be();
    });

  });

}));
