/**
 * Carbon
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CarbonJsSdk);
  }
}(this, function(expect, CarbonJsSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CarbonJsSdk.OrganizationUserFilesToSyncFilters();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OrganizationUserFilesToSyncFilters', function() {
    it('should create an instance of OrganizationUserFilesToSyncFilters', function() {
      // uncomment below and update the code to test OrganizationUserFilesToSyncFilters
      //var instance = new CarbonJsSdk.OrganizationUserFilesToSyncFilters();
      //expect(instance).to.be.a(CarbonJsSdk.OrganizationUserFilesToSyncFilters);
    });

    it('should have the property source (base name: "source")', function() {
      // uncomment below and update the code to test the property source
      //var instance = new CarbonJsSdk.OrganizationUserFilesToSyncFilters();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new CarbonJsSdk.OrganizationUserFilesToSyncFilters();
      //expect(instance).to.be();
    });

    it('should have the property tags (base name: "tags")', function() {
      // uncomment below and update the code to test the property tags
      //var instance = new CarbonJsSdk.OrganizationUserFilesToSyncFilters();
      //expect(instance).to.be();
    });

    it('should have the property tagsV2 (base name: "tags_v2")', function() {
      // uncomment below and update the code to test the property tagsV2
      //var instance = new CarbonJsSdk.OrganizationUserFilesToSyncFilters();
      //expect(instance).to.be();
    });

    it('should have the property ids (base name: "ids")', function() {
      // uncomment below and update the code to test the property ids
      //var instance = new CarbonJsSdk.OrganizationUserFilesToSyncFilters();
      //expect(instance).to.be();
    });

    it('should have the property externalFileIds (base name: "external_file_ids")', function() {
      // uncomment below and update the code to test the property externalFileIds
      //var instance = new CarbonJsSdk.OrganizationUserFilesToSyncFilters();
      //expect(instance).to.be();
    });

    it('should have the property syncStatuses (base name: "sync_statuses")', function() {
      // uncomment below and update the code to test the property syncStatuses
      //var instance = new CarbonJsSdk.OrganizationUserFilesToSyncFilters();
      //expect(instance).to.be();
    });

    it('should have the property parentFileIds (base name: "parent_file_ids")', function() {
      // uncomment below and update the code to test the property parentFileIds
      //var instance = new CarbonJsSdk.OrganizationUserFilesToSyncFilters();
      //expect(instance).to.be();
    });

    it('should have the property organizationUserDataSourceId (base name: "organization_user_data_source_id")', function() {
      // uncomment below and update the code to test the property organizationUserDataSourceId
      //var instance = new CarbonJsSdk.OrganizationUserFilesToSyncFilters();
      //expect(instance).to.be();
    });

    it('should have the property embeddingGenerators (base name: "embedding_generators")', function() {
      // uncomment below and update the code to test the property embeddingGenerators
      //var instance = new CarbonJsSdk.OrganizationUserFilesToSyncFilters();
      //expect(instance).to.be();
    });

  });

}));
