/**
 * Carbon
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CarbonJsSdk);
  }
}(this, function(expect, CarbonJsSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CarbonJsSdk.WebscrapeRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('WebscrapeRequest', function() {
    it('should create an instance of WebscrapeRequest', function() {
      // uncomment below and update the code to test WebscrapeRequest
      //var instance = new CarbonJsSdk.WebscrapeRequest();
      //expect(instance).to.be.a(CarbonJsSdk.WebscrapeRequest);
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instance = new CarbonJsSdk.WebscrapeRequest();
      //expect(instance).to.be();
    });

    it('should have the property tags (base name: "tags")', function() {
      // uncomment below and update the code to test the property tags
      //var instance = new CarbonJsSdk.WebscrapeRequest();
      //expect(instance).to.be();
    });

    it('should have the property recursionDepth (base name: "recursion_depth")', function() {
      // uncomment below and update the code to test the property recursionDepth
      //var instance = new CarbonJsSdk.WebscrapeRequest();
      //expect(instance).to.be();
    });

    it('should have the property maxPagesToScrape (base name: "max_pages_to_scrape")', function() {
      // uncomment below and update the code to test the property maxPagesToScrape
      //var instance = new CarbonJsSdk.WebscrapeRequest();
      //expect(instance).to.be();
    });

    it('should have the property chunkSize (base name: "chunk_size")', function() {
      // uncomment below and update the code to test the property chunkSize
      //var instance = new CarbonJsSdk.WebscrapeRequest();
      //expect(instance).to.be();
    });

    it('should have the property chunkOverlap (base name: "chunk_overlap")', function() {
      // uncomment below and update the code to test the property chunkOverlap
      //var instance = new CarbonJsSdk.WebscrapeRequest();
      //expect(instance).to.be();
    });

    it('should have the property skipEmbeddingGeneration (base name: "skip_embedding_generation")', function() {
      // uncomment below and update the code to test the property skipEmbeddingGeneration
      //var instance = new CarbonJsSdk.WebscrapeRequest();
      //expect(instance).to.be();
    });

    it('should have the property enableAutoSync (base name: "enable_auto_sync")', function() {
      // uncomment below and update the code to test the property enableAutoSync
      //var instance = new CarbonJsSdk.WebscrapeRequest();
      //expect(instance).to.be();
    });

    it('should have the property generateSparseVectors (base name: "generate_sparse_vectors")', function() {
      // uncomment below and update the code to test the property generateSparseVectors
      //var instance = new CarbonJsSdk.WebscrapeRequest();
      //expect(instance).to.be();
    });

    it('should have the property prependFilenameToChunks (base name: "prepend_filename_to_chunks")', function() {
      // uncomment below and update the code to test the property prependFilenameToChunks
      //var instance = new CarbonJsSdk.WebscrapeRequest();
      //expect(instance).to.be();
    });

    it('should have the property htmlTagsToSkip (base name: "html_tags_to_skip")', function() {
      // uncomment below and update the code to test the property htmlTagsToSkip
      //var instance = new CarbonJsSdk.WebscrapeRequest();
      //expect(instance).to.be();
    });

    it('should have the property cssClassesToSkip (base name: "css_classes_to_skip")', function() {
      // uncomment below and update the code to test the property cssClassesToSkip
      //var instance = new CarbonJsSdk.WebscrapeRequest();
      //expect(instance).to.be();
    });

    it('should have the property cssSelectorsToSkip (base name: "css_selectors_to_skip")', function() {
      // uncomment below and update the code to test the property cssSelectorsToSkip
      //var instance = new CarbonJsSdk.WebscrapeRequest();
      //expect(instance).to.be();
    });

  });

}));
