/**
 * Carbon
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CarbonJsSdk);
  }
}(this, function(expect, CarbonJsSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CarbonJsSdk.UtilitiesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UtilitiesApi', function() {
    describe('fetchUrlsFetchUrlsGet', function() {
      it('should call fetchUrlsFetchUrlsGet successfully', function(done) {
        //uncomment below and update the code to test fetchUrlsFetchUrlsGet
        //instance.fetchUrlsFetchUrlsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('fetchYoutubeTranscriptsFetchYoutubeTranscriptGet', function() {
      it('should call fetchYoutubeTranscriptsFetchYoutubeTranscriptGet successfully', function(done) {
        //uncomment below and update the code to test fetchYoutubeTranscriptsFetchYoutubeTranscriptGet
        //instance.fetchYoutubeTranscriptsFetchYoutubeTranscriptGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('scrapeSitemapScrapeSitemapPost', function() {
      it('should call scrapeSitemapScrapeSitemapPost successfully', function(done) {
        //uncomment below and update the code to test scrapeSitemapScrapeSitemapPost
        //instance.scrapeSitemapScrapeSitemapPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchUrlsSearchUrlsGet', function() {
      it('should call searchUrlsSearchUrlsGet successfully', function(done) {
        //uncomment below and update the code to test searchUrlsSearchUrlsGet
        //instance.searchUrlsSearchUrlsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('sitemapProcessSitemapGet', function() {
      it('should call sitemapProcessSitemapGet successfully', function(done) {
        //uncomment below and update the code to test sitemapProcessSitemapGet
        //instance.sitemapProcessSitemapGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('webScrapeWebScrapePost', function() {
      it('should call webScrapeWebScrapePost successfully', function(done) {
        //uncomment below and update the code to test webScrapeWebScrapePost
        //instance.webScrapeWebScrapePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
